### ISSUE TITLE
Great Project 👍

### ISSUE THREAD

**Issue by chrismbah** [Trayshmhirk/monsters-rolodex-react-app#1]
This was a very nice project especially for your first time. Although you don't have to worry much about props because trust me there's a much easier way of passing props in react. For me that prop syntax looked scary sha 😂

**Comment by Trayshmhirk** [comment]
Yeahhh.. i kept having to validate every prop. I'm just starting out sha, so i know there should be better ways of writing the code.
Thanks.

**Comment by chrismbah** [comment]
No problem boss
